services:
  app:
    build:
      context: .
    ports:
      - "8080:8080"
    environment:
      - SECRET_KEY=${SECRET_KEY:-your_secret_key_here}
      - DB_HOST=postgres
      - DB_NAME=quant_trading_db
      - DB_USER=postgres
      - DB_PASSWORD=${DB_PASSWORD:-jonawong.}
      - DB_PORT=5432
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - .:/app

  postgres:
    image: postgres:15
    environment:
      - POSTGRES_DB=quant_trading_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${DB_PASSWORD:-jonawong.}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pgdata: